run:
  timeout: 5m
  skip-files: []

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 13
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  forbidigo:
    forbid:
      - '^print(ln)?$'
      - '^spew\.Print(f|ln)?$'
      - '^spew\.Dump$'
  gomoddirectives:
    replace-allow-list:
      - github.com/abbot/go-http-auth
      - github.com/go-check/check
      - github.com/gorilla/mux
      - github.com/mailgun/minheap
      - github.com/mailgun/multibuf
      - github.com/jaguilar/vt100
  revive:
    rules:
      - name: struct-tag
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - cyclop # duplicate of gocyclo
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - lll
    - gosec
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - mnd
    - testpackage
    - paralleltest
    - tparallel
    - err113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - varnamelen
    - nilnil
    - gosmopolitan  # not relevant

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

