version: 2

project_name: traefik-certs-cleaner

builds:
  - binary: traefik-certs-cleaner
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    goarm:
      - '7'
      - '6'
      - '5'

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore\(deps\):'
      - '^test:'
      - '^tests:'

archives:
  - id: tcc
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE

dockers_v2:
  - images:
      - 'ldez/traefik-certs-cleaner'
    dockerfile: buildx.Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
      - linux/arm/v6
      - linux/386
    tags:
      - 'latest'
      - 'v{{ .Major }}'
      - 'v{{ .Major }}.{{ .Minor }}'
      - '{{ .Tag }}'
    labels:
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      'org.opencontainers.image.title': '{{.ProjectName}}'
      'org.opencontainers.image.description': 'Clean the Traefik acme.json file by removing and revoking certificates'
      'org.opencontainers.image.source': '{{.GitURL}}'
      'org.opencontainers.image.url': '{{.GitURL}}'
      'org.opencontainers.image.documentation': 'https://github.com/ldez/traefik-certs-cleaner'
      'org.opencontainers.image.created': '{{.Date}}'
      'org.opencontainers.image.revision': '{{.FullCommit}}'
      'org.opencontainers.image.version': '{{.Version}}'
